name = "heyting"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Heyting"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
weak.linter.style.whitespace = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0"

[[require]]
name = "repl"
git = "https://github.com/leanprover-community/repl"
rev = "v4.28.0" 

[[lean_lib]]
name = "Heyting"

[[lean_exe]]
name = "heytingc"
root = "Main"
