import Heyting.Core.CheckedSemantics
import Heyting.Core.Language
import Heyting.Core.SubstSemantics
import Heyting.Languages.FlatIR

/-!
# FlatIR Checked Substitution Semantics

Deterministic checked semantics for `FlatIR` phrased via symbolic atoms from
`SubstSemantics.CAtom`.

The evaluator returns either:
- `Result.success trace` containing all checked atoms, or
- `Result.failure checkedPrefix failed` at the first failing atom.

This module proves equivalence with existing `FlatIR.satisfies`.
-/
namespace FlatIRSubst

open CheckedSemantics
open SubstSemantics

variable {F : Type} [Field F]

abbrev Atom (F : Type) := CAtom F
abbrev ValSubst (F : Type) := SubstSemantics.ValSubst F
abbrev SWitness (F : Type) := SubstSemantics.Witness F

def defaultValuation : LocalVar → F := fun _ => 0
def defaultPathValuation : LocalVar → InstancePath := fun _ => []

/-- Flat witness viewed as substitution witness by ignoring instance paths. -/
def liftWitness (w : FlatIR.Witness F) : SWitness F := fun (_, member) => w member

/-- Initial value substitution reads concrete witness values as constants. -/
def initValSubst (w : FlatIR.Witness F) : ValSubst F :=
  fun v => .const (w v)

/-- Boolean checker for emitted atoms. -/
def checkAtom [DecidableEq F] (w : FlatIR.Witness F) (a : Atom F) : Bool :=
  match a with
  | .eq lhs rhs =>
    decide
      (VTerm.interp (liftWitness w) defaultValuation defaultPathValuation lhs =
        VTerm.interp (liftWitness w) defaultValuation defaultPathValuation rhs)
  | .neZero term =>
    decide (VTerm.interp (liftWitness w) defaultValuation defaultPathValuation term ≠ 0)

theorem checkAtom_true_iff [DecidableEq F] (w : FlatIR.Witness F) (a : Atom F) :
    checkAtom w a = true ↔
      CAtom.interp (liftWitness w) defaultValuation defaultPathValuation a := by
  cases a with
  | eq lhs rhs => simp [checkAtom, CAtom.interp]
  | neZero term => simp [checkAtom, CAtom.interp]

/-- Atom constraints generated by a FlatIR instruction under value substitution. -/
def atomsOfInstr (σv : ValSubst F) : FlatIR.Instr F → List (Atom F)
  | .assignAdd dest src1 src2 => [.eq (σv dest) (.add (σv src1) (σv src2))]
  | .assignSub dest src1 src2 => [.eq (σv dest) (.sub (σv src1) (σv src2))]
  | .assignMul dest src1 src2 => [.eq (σv dest) (.mul (σv src1) (σv src2))]
  | .assignDiv dest src1 src2 => [.neZero (σv src2), .eq (σv dest) (.div (σv src1) (σv src2))]
  | .assignNeg dest src => [.eq (σv dest) (.neg (σv src))]
  | .assignConst dest c => [.eq (σv dest) (.const c)]
  | .assertEq src1 src2 => [.eq (σv src1) (σv src2)]

/-- Flatten instruction atoms for the whole program. -/
def programAtoms (w : FlatIR.Witness F) (p : FlatIR.Program F) : List (Atom F) :=
  p.flatMap (atomsOfInstr (initValSubst w))

/-- Deterministic checked evaluation over a list of atoms. -/
def evalAtomsChecked [DecidableEq F] (w : FlatIR.Witness F) (atoms : List (Atom F)) :
    Result (Atom F) :=
  match atoms with
  | [] => Result.success []
  | a :: rest =>
    if checkAtom w a then
      match evalAtomsChecked w rest with
      | Result.success trace => Result.success (a :: trace)
      | Result.failure checkedPrefix failed => Result.failure (a :: checkedPrefix) failed
    else
      Result.failure [] a

/-- Deterministic checked evaluation for FlatIR via atom lowering. -/
def evalChecked [DecidableEq F] (w : FlatIR.Witness F) (prog : FlatIR.Program F) :
    Result (Atom F) :=
  evalAtomsChecked w (programAtoms w prog)

def checkedSuccess [DecidableEq F] (w : FlatIR.Witness F) (prog : FlatIR.Program F) : Prop :=
  ∃ trace, evalChecked w prog = Result.success trace

theorem evalAtomsChecked_success_iff_all [DecidableEq F]
    (w : FlatIR.Witness F) (atoms : List (Atom F)) :
    (∃ trace, evalAtomsChecked w atoms = Result.success trace) ↔
      ∀ a ∈ atoms, CAtom.interp (liftWitness w) defaultValuation defaultPathValuation a := by
  induction atoms with
  | nil =>
    simp [evalAtomsChecked]
  | cons a rest ih =>
    by_cases hca : checkAtom w a
    · have ha : CAtom.interp (liftWitness w) defaultValuation defaultPathValuation a :=
        (checkAtom_true_iff w a).1 hca
      constructor
      · intro h
        rcases h with ⟨trace, htrace⟩
        have hrestSucc : ∃ t, evalAtomsChecked w rest = Result.success t := by
          cases hrest : evalAtomsChecked w rest with
          | success t =>
            refine ⟨t, ?_⟩
            simp
          | failure checkedPrefix failed =>
            simp [evalAtomsChecked, hca, hrest] at htrace
        have hrestAll := ih.mp hrestSucc
        intro b hb
        rcases List.mem_cons.mp hb with rfl | hbRest
        · exact ha
        · exact hrestAll b hbRest
      · intro hall
        have hrestAll :
            ∀ b ∈ rest, CAtom.interp (liftWitness w) defaultValuation defaultPathValuation b := by
          intro b hb
          exact hall b (List.mem_cons_of_mem _ hb)
        rcases ih.mpr hrestAll with ⟨trace, htrace⟩
        refine ⟨a :: trace, ?_⟩
        simp [evalAtomsChecked, hca, htrace]
    · constructor
      · intro h
        simp [evalAtomsChecked, hca] at h
      · intro hall
        have ha : CAtom.interp (liftWitness w) defaultValuation defaultPathValuation a :=
          hall a (by simp)
        have : checkAtom w a = true := (checkAtom_true_iff w a).2 ha
        exact False.elim (hca this)

theorem atomsOfInstr_iff_satisfiesInstr (w : FlatIR.Witness F) (instr : FlatIR.Instr F) :
    (∀ a ∈ atomsOfInstr (initValSubst w) instr,
      CAtom.interp (liftWitness w) defaultValuation defaultPathValuation a) ↔
      FlatIR.satisfiesInstr w instr := by
  cases instr with
  | assignAdd dest src1 src2 =>
    simp [atomsOfInstr, FlatIR.satisfiesInstr, initValSubst, CAtom.interp, VTerm.interp]
  | assignSub dest src1 src2 =>
    simp [atomsOfInstr, FlatIR.satisfiesInstr, initValSubst, CAtom.interp, VTerm.interp]
  | assignMul dest src1 src2 =>
    simp [atomsOfInstr, FlatIR.satisfiesInstr, initValSubst, CAtom.interp, VTerm.interp]
  | assignDiv dest src1 src2 =>
    simp [atomsOfInstr, FlatIR.satisfiesInstr, initValSubst, CAtom.interp, VTerm.interp]
  | assignNeg dest src =>
    simp [atomsOfInstr, FlatIR.satisfiesInstr, initValSubst, CAtom.interp, VTerm.interp]
  | assignConst dest c =>
    simp [atomsOfInstr, FlatIR.satisfiesInstr, initValSubst, CAtom.interp, VTerm.interp]
  | assertEq src1 src2 =>
    simp [atomsOfInstr, FlatIR.satisfiesInstr, initValSubst, CAtom.interp, VTerm.interp]

theorem programAtoms_all_iff_satisfies (w : FlatIR.Witness F) (prog : FlatIR.Program F) :
    (∀ a ∈ programAtoms w prog,
      CAtom.interp (liftWitness w) defaultValuation defaultPathValuation a) ↔
      FlatIR.satisfies w prog := by
  induction prog with
  | nil =>
    simp [programAtoms, FlatIR.satisfies]
  | cons instr rest ih =>
    constructor
    · intro hall
      have hsInstr : FlatIR.satisfiesInstr w instr := by
        apply (atomsOfInstr_iff_satisfiesInstr w instr).1
        intro a ha
        exact hall a (by simp [programAtoms, ha])
      have hsRest : FlatIR.satisfies w rest := by
        apply ih.mp
        intro a ha
        unfold CAtom.interp
        have hh : a ∈ programAtoms w (instr :: rest) := by
          simp only [programAtoms, List.mem_flatMap, forall_exists_index, and_imp,
            List.flatMap_cons, List.mem_append] at *
          specialize hall a
          right
          exact ha
        exact hall a hh
      intro instr' hin
      rcases List.mem_cons.mp hin with rfl | hinRest
      · exact hsInstr
      · exact hsRest instr' hinRest
    · intro hs
      have hsInstr : FlatIR.satisfiesInstr w instr := hs instr (by simp)
      have hsRest : FlatIR.satisfies w rest := by
        intro instr' hin
        exact hs instr' (by simp [hin])
      have hallInstr : ∀ a ∈ atomsOfInstr (initValSubst w) instr,
          CAtom.interp (liftWitness w) defaultValuation defaultPathValuation a :=
        (atomsOfInstr_iff_satisfiesInstr w instr).2 hsInstr
      have hallRest : ∀ a ∈ programAtoms w rest,
          CAtom.interp (liftWitness w) defaultValuation defaultPathValuation a :=
        ih.mpr hsRest
      intro a ha
      have ha' : a ∈ atomsOfInstr (initValSubst w) instr ∨ a ∈ programAtoms w rest := by
        simpa [programAtoms] using ha
      rcases ha' with haInstr | haRest
      · exact hallInstr a haInstr
      · exact hallRest a haRest

theorem checkedSuccess_iff_satisfies [DecidableEq F]
    (w : FlatIR.Witness F) (prog : FlatIR.Program F) :
    checkedSuccess w prog ↔ FlatIR.satisfies w prog := by
  unfold checkedSuccess evalChecked
  constructor
  · intro h
    have hall := (evalAtomsChecked_success_iff_all w (programAtoms w prog)).1 h
    exact (programAtoms_all_iff_satisfies w prog).1 hall
  · intro hs
    have hall := (programAtoms_all_iff_satisfies w prog).2 hs
    exact (evalAtomsChecked_success_iff_all w (programAtoms w prog)).2 hall

theorem checkedSuccess_of_satisfies [DecidableEq F]
    (w : FlatIR.Witness F) (prog : FlatIR.Program F)
    (h : FlatIR.satisfies w prog) : checkedSuccess w prog :=
  (checkedSuccess_iff_satisfies w prog).2 h

theorem satisfies_of_checkedSuccess [DecidableEq F]
    (w : FlatIR.Witness F) (prog : FlatIR.Program F)
    (h : checkedSuccess w prog) : FlatIR.satisfies w prog :=
  (checkedSuccess_iff_satisfies w prog).1 h

def Language (F : Type) [Field F] : _root_.Language FlatIR.VarId F where
  Program := FlatIR.Program F
  satisfies := FlatIR.satisfies

end FlatIRSubst
